### ISSUE TITLE
Can't share from Google Photos

### ISSUE THREAD

**Issue by abarisain** [abarisain/skugga#1]
Google Photos provides a temporary URI. Since skugga passes it to a service, it fails.

02-05 13:14:07.853 18304 18325 E AndroidRuntime: Process: fr.nlss.skugga, PID: 18304
02-05 13:14:07.853 18304 18325 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.MediaContentProvider from ProcessRecord{e0de6df 18304:fr.nlss.skugga/u0a156} (pid=18304, uid=10156) that is not exported from uid 10063
02-05 13:14:07.853 18304 18325 E AndroidRuntime:    at fr.nlss.skugga.client.FileUploadClient.uriToJpeg(FileUploadClient.java:60)
02-05 13:14:07.853 18304 18325 E AndroidRuntime:    at fr.nlss.skugga.client.FileUploadClient.uploadUri(FileUploadClient.java:76)
02-05 13:14:07.853 18304 18325 E AndroidRuntime:    at fr.nlss.skugga.service.UploadService.handleUploadAction(UploadService.java:81)
02-05 13:14:07.853 18304 18325 E AndroidRuntime:    at fr.nlss.skugga.service.UploadService.onHandleIntent(UploadService.java:68)
02-06 18:58:37.982  4918  7059 I ActivityManager: START u0 {act=android.intent.action.SEND typ=image/jpeg flg=0x10000001 cmp=fr.nlss.skugga/.DummyShareActivity clip={image/jpeg U:content://com.google.android.apps.photos.contentprovider/1/1/mediaKey%3A%2FAF1QipMF2h_iXnxI9bsgouPCyLS4GFE8Y4QovXeJvONO/FORMAT_JPEG/1394123923} (has extras)} from uid 10063 on display 0
02-06 18:58:38.097  4918 14267 I ActivityManager: Start proc 17268:fr.nlss.skugga/u0a156 for activity fr.nlss.skugga/.DummyShareActivity
02-06 18:58:38.595  4918 24923 I ActivityManager: Process fr.nlss.skugga (pid 17268) has died

Low power mode triggers an activity because of the "no background activity" policy, so it works.

**Comment by webbrain-one** [comment]
Hi! Thanks for the detailed report. I've just opened a PR to address this: https://github.com/abarisain/skugga/pull/2

The fix properly handles temporary URIs from Google Photos by ensuring the image is securely processed in the foreground before being passed to the background upload service, which resolves the `SecurityException`. Sharing should now work smoothly without needing the low-power mode workaround.

Let me know if you run into any other issues! Thanks again for reporting this. 🙌
